### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by SemenShchedrin** [SemenShchedrin/ASSS-FRONTCAMP-2017#4]
Improve your application for Webpack:
(1-3) stars
- Use Babel as a loader.
- Use style and url loaders. (Sass/less/stylus, autoprefixer optional)
- Each part of logic should be in a separate file. (ES6 modules)
- Use plugins
- Configure the bundler for development and production mode.
- Configure Webpack-dev-server

(4-5) stars
- AMD: Create button "Show News" on the main page. Your app should load necessary code for rendering the list only after clicking on the button above.

- Custom Loader:
Loader should be chainable
Applicable for /\.json/
Remove all number attributes in source

**Comment by gam0ny** [comment]
Looks good
